import type { Metadata } from "next";
import { Jost, Libre_Caslon_Text } from "next/font/google";
import "./globals.css";
import OfferHeader from "@/components/header/OfferHeader";
import Header from "@/components/header/Header";
import Footer from "@/components/AiComponents/Footer";
import ReduxProvider from "@/redux/ReduxProvider";
import GetQuoteDialog from "@/components/Dialogs/AiDialogs/GetQuoteDialog";
import AiHeaderHolder from "@/components/AiComponents/AiHeaderHolder";
import Slider from "@/components/Slider";
import React from "react";
import { CustomGalleryDialog } from "@/components/Dialogs/CustomGalleryDialog";

const jostFont = Jost({
  variable: "--font-jost",
  subsets: ["latin"],
});

const libreCaslonFont = Libre_Caslon_Text({
  variable: "--libre-caslon-text",
  subsets: ["latin"],
  weight: ["400", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${jostFont.variable} ${libreCaslonFont.variable} antialiased mx-auto max-w-[1920px] max-sm:max-w-full max-sm:w-full overflow-x-hidden m-0 p-0`}
      >
        <ReduxProvider>
          <CustomGalleryDialog />
          <Slider />
          <GetQuoteDialog />
          <OfferHeader />
          <AiHeaderHolder>
            <Header />
          </AiHeaderHolder>
          <main className="mt-3.5 w-full overflow-x-hidden">
            <React.Suspense>{children}</React.Suspense>
          </main>
          <Footer />
        </ReduxProvider>
      </body>
    </html>
  );
}
